version: '2'

services:
  nginx:
    image: nginx
    ports:
      - 8086:80
    volumes:
      - ./:/var/www/sylius
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm
      - varnish

  fpm:
    build: docker/php-fpm/
    links:
      - mysql
    volumes:
      - ./:/var/www/sylius
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: sylius_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  varnish:
    build: docker/varnish/